// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyChatApi.Models;

public partial class OneToOneMessage
{
    public string Id { get; set; }

    public string ConversationId { get; set; }

    public string Message { get; set; }

    public DateTime SendDateTime { get; set; }

    public string SenderId { get; set; }

    public virtual OneToOneConversation Conversation { get; set; }

    public virtual User Sender { get; set; }
}