// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyChatApi.Models;

public partial class OneToOneConversation
{
    public string Id { get; set; }

    public string SenderId { get; set; }

    public string RecieverId { get; set; }

    public DateTime LastMessagedOn { get; set; }

    public virtual ICollection<OneToOneMessage> OneToOneMessages { get; set; } = new List<OneToOneMessage>();

    public virtual User Reciever { get; set; }

    public virtual User Sender { get; set; }
}