// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyChatApi.Models;

public partial class User
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public virtual ICollection<OneToOneConversation> OneToOneConversationRecievers { get; set; } = new List<OneToOneConversation>();

    public virtual ICollection<OneToOneConversation> OneToOneConversationSenders { get; set; } = new List<OneToOneConversation>();

    public virtual ICollection<OneToOneMessage> OneToOneMessages { get; set; } = new List<OneToOneMessage>();
}